//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiTree.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdiTree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dividelist_24x24 {
            get {
                object obj = ResourceManager.GetObject("dividelist_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Divide a list into sub-lists by the predefined number (divisor).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dividelist_description {
            get {
                return ResourceManager.GetString("dividelist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Divide a list into sub-lists by the predefined number (divisor). Any remaining item will be stored in the seperate path followed by last branch.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dividelist_description_full {
            get {
                return ResourceManager.GetString("dividelist_description_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EdiTree is a set of useful open source components developed by EDIT Collective to provide easier
        ///manipulation of data structure and data management.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string editree_description {
            get {
                return ResourceManager.GetString("editree_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap editree_logo {
            get {
                object obj = ResourceManager.GetObject("editree_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap partitionlist_24x24 {
            get {
                object obj = ResourceManager.GetObject("partitionlist_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Partition a list into sub-lists by partition size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string partitionlist_description {
            get {
                return ResourceManager.GetString("partitionlist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap splitlistmulti_24x24 {
            get {
                object obj = ResourceManager.GetObject("splitlistmulti_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Split a list into separate parts at a specified index number. Similar to the existing Split List Component, each index indicates the first item in each list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splitlistmulti_description {
            get {
                return ResourceManager.GetString("splitlistmulti_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split a list into separate parts at a specified index number. Similar to the existing Split List Component, each index indicates the first item in each list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splitlistmulti_description_full {
            get {
                return ResourceManager.GetString("splitlistmulti_description_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap subtree_24x24 {
            get {
                object obj = ResourceManager.GetObject("subtree_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Retrieve a specific branch / sub-branches from a data tree.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string subtree_description {
            get {
                return ResourceManager.GetString("subtree_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve a specific branch / sub-branches from a data tree. This component allows you to extract items under the specified branch, when branch path indices are assigned.
        ///&lt;BR&gt;
        ///&lt;BR&gt;
        ///Should the path index at placeholders be not assigned, the component will interpret the
        ///value of the path index as “?”.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string subtree_description_full {
            get {
                return ResourceManager.GetString("subtree_description_full", resourceCulture);
            }
        }
    }
}
